import { eventRecorder } from "@/hooks/event-recorder";
import { createHook } from "@/hooks/hook-generator";
import type { HookCommand, HookEventName } from "@/types/hooks";

type BuiltinCommands = Record<HookEventName, HookCommand>;

const builtins: BuiltinCommands = {
  ConfigChange: createHook({
    event: "ConfigChange",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  CwdChanged: createHook({
    event: "CwdChanged",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  FileChanged: createHook({
    event: "FileChanged",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  Notification: createHook({
    event: "Notification",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  PermissionRequest: createHook({
    event: "PermissionRequest",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  PostToolUse: createHook({
    event: "PostToolUse",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  PostToolUseFailure: createHook({
    event: "PostToolUseFailure",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  PostCompact: createHook({
    event: "PostCompact",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  PreCompact: createHook({
    event: "PreCompact",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  PreToolUse: createHook({
    event: "PreToolUse",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  SessionEnd: createHook({
    event: "SessionEnd",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  SessionStart: createHook({
    event: "SessionStart",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  Setup: createHook({
    event: "Setup",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  Stop: createHook({
    event: "Stop",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  StopFailure: createHook({
    event: "StopFailure",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  SubagentStart: createHook({
    event: "SubagentStart",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  SubagentStop: createHook({
    event: "SubagentStop",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  TaskCompleted: createHook({
    event: "TaskCompleted",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  TaskCreated: createHook({
    event: "TaskCreated",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  TeammateIdle: createHook({
    event: "TeammateIdle",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  UserPromptSubmit: createHook({
    event: "UserPromptSubmit",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  WorktreeCreate: createHook({
    event: "WorktreeCreate",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  WorktreeRemove: createHook({
    event: "WorktreeRemove",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  InstructionsLoaded: createHook({
    event: "InstructionsLoaded",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  Elicitation: createHook({
    event: "Elicitation",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
  ElicitationResult: createHook({
    event: "ElicitationResult",
    id: "builtin-recorder",
    source: "builtin",
    batchable: true,
    handler: eventRecorder.record,
  }),
};

export const getBuiltinHookCommands = () => builtins;
